# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JWT'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
#  pod 'WPMarkDownParse'
  pod "YYModel"
#  pod 'YYText'
  pod 'YYKit'
#  pod "markymark"
  # Pods for ChatAI

  target 'ChatAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAIUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end

  
  

  
  
end
